version: "3.8"
services:
  backend:
    build: 
      context: backend
      dockerfile: DockerFile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    tty: true
    ports: 
      - "8080:8080"
    volumes:
      - ./backend/app:/app/app
      - ./backend/metaphlan_db:/app/metaphlan_db
      - ./backend/data:/app/data

  frontend:
    build:
      context: frontend
      dockerfile: DockerFile
    tty: true
    ports: 
      - "80:80"
    volumes:
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/src:/app/src/
      - notused:/app/node_modules
    environment:
      VITE_API_URL: ${VITE_API_URL}

volumes:
  notused: