FROM python:3.9-slim as base

ENV PYTHONHASHSEED=random \
    PYTHONUNBUFFERED=1 
    # PYTHONFAULTHANDLER=1 - Display trace if a sefault occurs.

RUN apt-get update && apt-get install -y gcc libffi-dev g++ bowtie2
WORKDIR /app

FROM base as builder

ENV PIP_DEFAULT_TIMEOUT=100 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    POETRY_VERSION=1.1.3

RUN pip install "poetry==$POETRY_VERSION"
RUN python -m venv /venv

COPY pyproject.toml poetry.lock ./
RUN . /venv/bin/activate && poetry install --no-root 

COPY . .

FROM base as final

COPY --from=builder /venv /venv
COPY --from=builder /app .

ENV PATH="/venv/bin:$PATH"